### ISSUE TITLE
Project needs a license

### ISSUE THREAD

**Issue by garethsaxby** [coskunbalta/cpuloadrepo#2]
If you're going to put a project up on public GitHub and make it available for the consumption of others, you should really attach a license to the project; MIT or GPLv2 are good options, but it's up to you.

**Comment by garethsaxby** [comment]
I should clarify this a bit more; it's important to include a license on projects uploaded to GitHub, because the repository is itself covered by Copyright laws without explicit licensing.
It's not a mandatory requirement, however it's usually a good idea to apply a license of some description to a GitHub project.

You might want to check out [Choose a License](http://choosealicense.com/) for details of what licenses you may want to choose from, or check out this [GitHub Help article](https://help.github.com/articles/open-source-licensing/) for details of how licensing applies to GitHub projects.

**Comment by coskunbalta** [comment]
Thanks Gareth I will have a look into this @garethsaxby

**Comment by coskunbalta** [comment]
Completed
